name: Run Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Start the app
      run: |
        cd backend
        python app.py &
        APP_PID=$!
        echo "APP_PID=$APP_PID" >> $GITHUB_ENV
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run tests
      run: |
        pytest

    - name: Stop the app
      run: |
        kill $APP_PID